import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Inter } from "next/font/google";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

const inter = Inter({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="p-3">{children}</body>
    </html>
  );
}
